# Use postgres/example user/password credentials
version: '3.1'

services:

    db:
        image: postgres
        restart: unless-stopped
        volumes:
            - ./database/main.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: nzqa
            POSTGRES_PASSWORD: nzqa
            POSTGRES_DB: nzqa

    api_service:
        build: 
            context: ./backend
        restart: unless-stopped
        volumes:
            - ./backend/code:/code
        environment:
            POSTGRES_USER: nzqa
            POSTGRES_PASSWORD: nzqa
            POSTGRES_DB: nzqa
        ports:
            - 3000:3000
    
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
            
    web_server:
        image: nginx
        volumes:
            - ./static:/usr/share/nginx/html/
        ports:
            - 8090:80
