version: '3.1'

services:

    db:
        image: postgres
        restart: unless-stopped
        volumes:
            - ./database/main.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: nzqa
            POSTGRES_PASSWORD: nzqa
            POSTGRES_DB: nzqa

    api_service:
        build: 
            context: ./backend
        restart: unless-stopped
        volumes:
            - ./backend/code:/code
        environment:
            POSTGRES_USER: nzqa
            POSTGRES_PASSWORD: nzqa
            POSTGRES_DB: nzqa
        ports:
            - 5000:5000
    
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
        
    caddy:
        image: caddy:2.0.0-alpine
        ports:
            - 80:80
            - 443:443
        user: root
        volumes:
            - ./static:/static
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./certs/config:/root/.config/caddy
            - ./certs/local:/root/.local/share/caddy
            - ./certs/data:/data
            - ./certs/local-config:/config
    scraper:
        build:
            context: ./scrape
        depends_on:
            - 'db'
        restart: unless-stopped
        volumes:
            - ./scrape/code:/code
            - ./scrape/output:/output
            - ./scrape/cache:/cache
        environment:
            FORCE_SCRAPE: 0
            HARD_CACHE: 1
            POSTGRES_USER: nzqa
            POSTGRES_PASSWORD: nzqa
            POSTGRES_DB: nzqa
            
    analytics:
        image: allinurl/goaccess
        depends_on:
            - 'caddy'
        restart: unless-stopped
        volumes:
            - ./static:/static
            - ./goaccess/:/etc/goaccess
        command: ['/static/analytics/access.log']

    search:
        image: getmeili/meilisearch:latest
        restart: unless-stopped
